app/main/views.py
from flask import Blueprint, render_template, session, redirect, url_for, current_app, request, flash, Response
from app.models import User, Participants, Winner, Archive, WinnerArchive
from app.auth.views import current_user, get_current_user
from app.auth.forms import LoginForm
import os, time, random, io
import xlwt
from app import db
import pandas as pd

main = Blueprint('main', __name__, template_folder='templates')

@main.route('/')
def home():
    if request.cookies.get("user_id"):
        form = LoginForm()
        #current_user = get_current_user()
        return render_template("home.html", form=form)
    return redirect(url_for('auth.login'))

# Get the uploaded files
@main.route("/upload", methods=['POST'])
def uploadFiles():
    if request.cookies.get("user_id"):
        # get the uploaded file
        uploaded_file = request.files['file']
        if uploaded_file.filename != '':
            file_path = os.path.join(current_app.config["UPLOAD_FOLDER"], uploaded_file.filename)
            # set the file path
            uploaded_file.save(file_path)
            participant = Participants.query.all()
            winner = Winner.query.all()
            for row in participant:
                archive = Archive(row.visionOuc, row.oucDescription, row.schemeCode, row.accountNo, row.accountName, row.accountOpenDate, row.phoneNumber)
                db.session.add(archive)
                db.session.query(Participants).delete()
                db.session.query(Winner).delete()
                db.session.commit()
            parseCSV(file_path)
        return redirect(url_for('main.getParticipants'))
    return redirect(url_for('auth.login'))


def parseCSV(filePath):
    # CVS Column Names
    col_names = ['visionOuc', 'oucDescription', 'schemeCode', 'accountNo', 'accountName', 'accountOpenDate', 'phoneNumber']
    # Use Pandas to parse the CSV file
    csvData = pd.read_csv(filePath, names=col_names, sep=';', header=0)
    # Loop through the Rows
    for i, row in csvData.iterrows():
        participant = Participants(row['visionOuc'], row['oucDescription'], row['schemeCode'], row['accountNo'], row['accountName'], row['accountOpenDate'], row['phoneNumber'])
        db.session.add(participant)
        db.session.commit()

ROWS_PER_PAGE = 5

@main.route('/paritcipant')
def getParticipants():
    if request.cookies.get("user_id"):
        # Set the pagination configuration
        page = request.args.get('page', 1, type=int)

        data = Participants.query.paginate(page=page, per_page=ROWS_PER_PAGE)
        if data:
            return render_template('listParticipants.html', data=data)
        return redirect(url_for('main.home'))
    return redirect(url_for('auth.login'))

@main.route('/download')
def downloadReport():
    liste = []
    if request.cookies.get("user_id"):
        data = Winner.query.all()

        output = io.BytesIO()
        workbook = xlwt.Workbook()
        sh = workbook.add_sheet('Vainqueur')

        sh.write(0, 0, 'VISION_OUC')
        sh.write(0, 1, 'OUC_DESCRIPTION')
        sh.write(0, 2, 'SCHEME_CODE')
        sh.write(0, 3, 'ACCOUNT_NO')
        sh.write(0, 4, 'ACCOUNT_NAME')
        sh.write(0, 5, 'ACCOUNT_OPEN_DATE')
        sh.write(0, 6, 'PHONE_NUMBER')

        idx = 0
        for item in data:
            sh.write(idx + 1, 0, item.visionOuc)
            sh.write(idx + 1, 1, item.oucDescription)
            sh.write(idx + 1, 2, item.schemeCode)
            sh.write(idx + 1, 3, item.accountNo)
            sh.write(idx + 1, 4, item.accountName)
            sh.write(idx + 1, 5, item.accountOpenDate)
            sh.write(idx + 1, 6, item.phoneNumber)
            idx += 1

        workbook.save(output)
        output.seek(0)

        return Response(output, mimetype="application/ms-excel",
                        headers={"Content-Disposition": "attachement;filename=Vainqueurs.xls"})
    return redirect(url_for('auth.login'))

@main.route('/winner')
def getWinner():
    if request.cookies.get("user_id"):
        # Set the pagination configuration
        page = request.args.get('page', 1, type=int)

        data = Winner.query.paginate(page=page, per_page=ROWS_PER_PAGE)
        if data:
            return render_template('listWinner.html', data=data)
        return redirect(url_for('main.home'))
    return redirect(url_for('auth.login'))

@main.route('/selectWinner', methods=['POST'])
def winner():
    my_list = []
    list_winner = []
    liste = []
    if request.cookies.get("user_id"):
        time.sleep(30)
        data = Participants.query.all()
        my_list = [row.accountNo for row in data]
        elt = random.choice(my_list)
        winner = Participants.query.filter_by(accountNo=elt).first()
        data_winner = Winner(winner.visionOuc, winner.oucDescription, winner.schemeCode, winner.accountNo, winner.accountName, winner.accountOpenDate, winner.phoneNumber)
        winnerArchive = WinnerArchive(winner.visionOuc, winner.oucDescription, winner.schemeCode, winner.accountNo, winner.accountName, winner.accountOpenDate, winner.phoneNumber)
        db.session.add(data_winner)
        db.session.add(winnerArchive)
        db.session.query(Participants).filter_by(accountNo=elt).delete()
        db.session.commit()
        flash('Le Numéro de  compte ' + winner.accountNo + ' a été selectionné')
        return redirect(url_for('main.getParticipants'))
    return redirect(url_for('auth.login'))


# @main.route('/')
# def home():
# 	users = User.query.all()
# 	return render_template('home.html', users=users)

app/main/templates/game.html
{% extends "base.html" %}

{% block title %} Title {% endblock %}
{% block content %}
    <h1>{{message}}</h1>
<button name="distance" type="submit" class="btn btn-secondary" value="10">Save</button>
{% endblock %}

app/main/templates/home.html
 {% if current_user.is_authenticated() %}

{% extends "base.html" %}

{% block title %} Title {% endblock %}
{% block content %}
<!--    <h1>Upload your CSV file</h1>-->
<!--    <form method="POST" action="" enctype="multipart/form-data">-->
<!--      <p><input type="file" name="file"></p>-->
<!--      <p><input type="submit" value="Submit"></p>-->
<!--    </form>-->
<div class="form mt-5 ml-5 pl-5">
    <!--<div class="card1">-->
    <form method="POST" action="/upload" enctype="multipart/form-data">
<div class="file-upload shadow bg-white rounded">
  <button class="file-upload-btn" type="button" onclick="$('.file-upload-input').trigger( 'click' )">Ajouter Fichier</button>

  <div class="image-upload-wrap">
    <input class="file-upload-input" type='file' onchange="readURL(this);" name="file"/>
    <div class="drag-text">
      <h3>Clicker ici pour choisir le fichier </h3>
    </div>
  </div>
  <div class="file-upload-content">
    <div class="image-title-wrap">
      <button type="button" onclick="removeUpload()" class="remove-image">Remove <span class="image-title">Uploaded Image</span></button>
      <br/><br/>
        <button class="file-upload-btn" type="submit" value="submit">Save</button>
    </div>
  </div>
</div>
    </form>
        <!--</div>-->
</div>
<!--/.Card-->
{% endblock %}

 {% else %}
 {% extends "login.html" %}
 {% endif %}

app/main/templates/listParticipants.html
{% extends "base.html" %}

{% block title %} Title {% endblock %}

{% block content %}


<div class="list">
  {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
            {% if category == 'message' %}
              <div class="alert alert-success" role="alert">
            {% else %}
              <div class="alert alert-{{ category }}" role="alert">
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
            {% endif %}
              <div class="message">{{ message }}</div>
            </div>

        {% endfor %}
      {% endif %}
  {% endwith %}
<div id="loading"></div>

<form method="POST" id="testForm" action="/selectWinner">
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Vision</th>
      <th scope="col">Scheme Code</th>
      <th scope="col">Account Number</th>
      <th scope="col">Account Name</th>
      <th scope="col">Phone Number</th>
    </tr>
  </thead>
  {% for item in data.items %}
  <tbody>
    <tr>

      <td>{{item.visionOuc}}</td>
      <td>{{item.schemeCode}}</td>
      <td>{{item.accountNo}}</td>
      <td>{{item.accountName}}</td>
      <td>{{item.phoneNumber}}</td>
    </tr>
  </tbody>
             {% endfor %}
</table>

<button type="submit" value="Submit" class="btn btn-success" data-toggle="modal" data-target="#loadMe">Selectionner</button>

</form>
<!-- Modal -->
<div class="modal fade" id="loadMe" tabindex="-1" data-backdrop="static" role="dialog" aria-labelledby="loadMeLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-body text-center">
        <div class="loader"></div>
        <div clas="loader-txt">
          <p> Dans 30 secondes nous allons sélectionner un client. <br><br><small> Etes-vous prêt... #UBA</small></p>
            <img class="img-gif" src="{{ url_for('static', filename='gif-time.gif') }}" alt="">
        </div>
      </div>
    </div>
  </div>
</div>


<!-- Pagination Links-->
<div class="text-right">
    <a href="{{ url_for('main.getParticipants', page=data.prev_num) }}"
       class="btn btn-outline-dark
       {% if data.page == 1 %}disabled{% endif %}">
        &laquo;
    </a>
<!-- Loop through the number of pages to display a link for each-->
    {% for page_num in data.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
<!-- Check for the active page and set the link to "Active"-->
            {% if data.page == page_num %}
            <a href="{{ url_for('main.getParticipants', page=page_num) }}"
               class="btn btn-dark">
                {{ page_num }}
            </a>
            {% else %}
            <a href="{{ url_for('main.getParticipants', page=page_num) }}"
               class="btn btn-outline-dark">
                {{ page_num }}
            </a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    <a href="{{ url_for('main.getParticipants', page=data.next_num) }}"
       class="btn btn-outline-dark
       {% if data.page == data.pages %}disabled{% endif %}">
        &raquo;
    </a>
</div>
<p class="text-right mt-3">
    {{ data.page }} of {{ data.pages }}
</p>

</div>

<script>
$(document).ready(function() {
    $('#loadMe').on('shown.bs.modal', function () {
    $("#loadMe").modal({
      backdrop: "static", //remove ability to close modal with click
      keyboard: false, //remove option to close with keyboard
      show: true //Display loader!
    });
    setTimeout(function() {
      $("#loadMe").modal("hide");
    }, 30000);
})
});
</script>
</div>
{% endblock %}

app/main/templates/listWinner.html
{% extends "base.html" %}

{% block title %} Title {% endblock %}
{% block content %}

<div class="list">
<!--<form method="POST" action="/selectWinner">-->
  <a class="btn btn-success" href="{{ url_for('main.downloadReport') }}" role="button">Générer Excel</a>
<table  class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Vision</th>
      <th scope="col">Scheme Code</th>
      <th scope="col">Account Number</th>
      <th scope="col">Account Name</th>
      <th scope="col">Phone Number</th>
    </tr>
  </thead>
  {% for item in data.items %}
  <tbody>
    <tr>
      <td>{{item.visionOuc}}</td>
      <td>{{item.schemeCode}}</td>
      <td>{{item.accountNo}}</td>
      <td>{{item.accountName}}</td>
      <td>{{item.phoneNumber}}</td>
    </tr>
  </tbody>
             {% endfor %}
</table>

<!--</form>-->
    <!-- Pagination Links-->
<div class="text-right">
    <a href="{{ url_for('main.getWinner', page=data.prev_num) }}"
       class="btn btn-outline-dark
       {% if data.page == 1 %}disabled{% endif %}">
        &laquo;
    </a>
<!-- Loop through the number of pages to display a link for each-->
    {% for page_num in data.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
<!-- Check for the active page and set the link to "Active"-->
            {% if data.page == page_num %}
            <a href="{{ url_for('main.getWinner', page=page_num) }}"
               class="btn btn-dark">
                {{ page_num }}
            </a>
            {% else %}
            <a href="{{ url_for('main.getWinner', page=page_num) }}"
               class="btn btn-outline-dark">
                {{ page_num }}
            </a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    <a href="{{ url_for('main.getWinner', page=data.next_num) }}"
       class="btn btn-outline-dark
       {% if data.page == data.pages %}disabled{% endif %}">
        &raquo;
    </a>
</div>
<p class="text-right mt-3">
    {{ data.page }} of {{ data.pages }}
</p>
</div>


{% endblock %}